#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GENERATED=0
#Hack: stat is different for OSX
if [[ "$OSTYPE" == "darwin"* ]]; then
  MAP_AST_CHANGED=$((`stat -f "%c" src/interfaces/ast/map-ast.ts` - `stat -f "%c" src/interfaces/ast/map-ast.schema.json`))
  PROFILE_AST_CHANGED=$((`stat -f "%c" src/interfaces/ast/profile-ast.ts` - `stat -f "%c" src/interfaces/ast/profile-ast.schema.json`))
  SUPERJSON_AST_CHANGED=$((`stat -f "%c" src/interfaces/superjson/superjson.ts` - `stat -f "%c" src/interfaces/superjson/superjson.schema.json`))
else
  MAP_AST_CHANGED=$((`stat --format="%Y" src/interfaces/ast/map-ast.ts` - `stat --format="%Y" src/interfaces/ast/map-ast.schema.json`))
  PROFILE_AST_CHANGED=$((`stat --format="%Y" src/interfaces/ast/profile-ast.ts` - `stat --format="%Y" src/interfaces/ast/profile-ast.schema.json`))
  SUPERJSON_AST_CHANGED=$((`stat --format="%Y" src/interfaces/superjson/superjson.ts` - `stat --format="%Y" src/interfaces/superjson/superjson.schema.json`))
fi


if [ $MAP_AST_CHANGED -gt 0 ]; then
  yarn run --silent generate_map_schema
  GENERATED=1
fi

if [ $PROFILE_AST_CHANGED -gt 0 ]; then
  yarn run --silent generate_profile_schema 
  GENERATED=1
fi

if [ $SUPERJSON_AST_CHANGED -gt 0 ]; then
  yarn run --silent generate_superjson_schema 
  GENERATED=1
fi

if [ $GENERATED -eq 1 ]; then
  echo "Some TypeScript schemas were modified. Their corresponding JSON schemas were attempted to be regenerated automatically."
  echo "Don't forget to commit them."
  echo "If you are sure you don't need to update the schemas, run 'git commit --no-verify'. "
  exit 1
fi
