#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GENERATED=0
#Hack: stat is different for OSX
if [[ "$OSTYPE" == "darwin"* ]]; then
  PROFILE_AST_CHANGED=$((`stat -f "%c" src/interfaces/ast/profile-ast.ts` - `stat -f "%c" src/interfaces/ast/profile-ast.schema.json`))
  PROVIDERJSON_AST_CHANGED=$((`stat -f "%c" src/interfaces/providerjson/providerjson.ts` - `stat -f "%c" src/interfaces/providerjson/providerjson.schema.json`))
else
  PROFILE_AST_CHANGED=$((`stat --format="%Y" src/interfaces/ast/profile-ast.ts` - `stat --format="%Y" src/interfaces/ast/profile-ast.schema.json`))
  PROVIDERJSON_AST_CHANGED=$((`stat --format="%Y" src/interfaces/providerjson/providerjson.ts` - `stat --format="%Y" src/interfaces/providerjson/providerjson.schema.json`))
fi

if [ $PROFILE_AST_CHANGED -gt 0 ]; then
  yarn run --silent generate_profile_schema 
  GENERATED=1
fi

if [ $PROVIDERJSON_AST_CHANGED -gt 0 ]; then
  yarn run --silent generate_providerjson_schema 
  GENERATED=1
fi

if [ $GENERATED -eq 1 ]; then
  echo "Some TypeScript schemas were modified. Their corresponding JSON schemas were attempted to be regenerated automatically."
  echo "Don't forget to commit them."
  echo "If you are sure you don't need to update the schemas, run 'git commit --no-verify'. "
  exit 1
fi
