name: Publish
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@superindustries"
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Publish Info
        run: |
          echo Publishing as version ${GITHUB_REF##*/v}
      - name: Publish
        run: yarn publish --version ${GITHUB_REF##*/v}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
